---
name: Generate XMLTV data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6,18 * * *'

jobs:
  generate_xmltv:
    runs-on: ubuntu-latest
    steps:
      - name: Check out maximushugus/tv_grab_fr_teleloisirs repository
        uses: actions/checkout@v2
        with:
          repository: maximushugus/tv_grab_fr_teleloisirs
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Python packages
        run: pip install -r requirements.txt
      - name: Configure grabber
        run: |-
          rm -f tv_grab_fr_teleloisirs.conf
          for id in $XMLTV_IDS; do
              echo "channel=$id.api-tel.programme-tv.net" >>tv_grab_fr_teleloisirs.conf
          done
        env:
          XMLTV_IDS: 4 30 33 34 35 47 76 78 80 100 112 116 118 119 145 147 156 192 195 226 234 243 282 283 284 285 287 400 401 402 439 444 445 446 458 481 482 529 662 675 681 719 730 732 733 734 781 1290 1304 1335 1336 1337 1228 1339 1340 1341 1342 1382 1399 1400 1401 1402 1562 1563 1944 2029 2072 2095 2111 2391 2441 2665 2666 2667 2668 2669 2670 2671 2672 2673 2674 2675 2676 2677 2678 2679 2837 3171 3172 183 202 3352 1404
      - name: Run grabber
        run: python tv_grab_fr_teleloisirs.py --config-file tv_grab_fr_teleloisirs.conf --days 7 --output xmltv_teleloisirs.xml
        env:
          TZ: Europe/Paris
      - name: Upload XMLTV file
        uses: actions/upload-artifact@v2
        with:
          name: xmltv
          path: xmltv_teleloisirs.xml
  export_xmltv:
    needs:
      - generate_xmltv
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Download XMLTV file
        uses: actions/download-artifact@v2
        with:
          name: xmltv
          path: .
      - name: Add XMLTV file to repository
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add xmltv_teleloisirs.xml
          if ! git diff-index --cached --quiet HEAD --; then
              git commit -m "$(date)"
              git push
          fi
